#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'py01-topic==0.0.0','console_scripts','demo01_talker_str_py'
__requires__ = 'py01-topic==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('py01-topic==0.0.0', 'console_scripts', 'demo01_talker_str_py')()
    )
